version: '3.8'

services:
  db-rag: 
    image: pgvector/pgvector:pg16
    container_name: postgres-vector-rag
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: InfoMaisSaude-RagArchitecture
    ports:
      - "5434:5432" 
    volumes:
      - ./pgdata_rag:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app-rag:
    build: .
    container_name: infomaissaude-backend-rag
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-rag:5432/InfoMaisSaude-RagArchitecture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      META_API_TOKEN: ${META_API_TOKEN}
      META_PHONE_ID: ${META_PHONE_ID}
      META_WEBHOOK_VERIFY_TOKEN: ${META_WEBHOOK_VERIFY_TOKEN}
    depends_on:
      - db-rag

  caddy-rag:
    image: caddy:latest
    container_name: caddy-rag-https
    restart: always
    ports:
      - "81:80"   
      - "444:443" 
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data_rag:/data
    depends_on:
      - app-rag

volumes:
  caddy_data_rag: